sonar.projectKey=flowboard-frontend
sonar.projectName=FlowBoard Frontend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=src/**/*.spec.ts,src/**/*.test.ts,src/main.ts,src/app/app.config.ts,src/app/app.routes.ts,src/environments/**,src/app/core/services/**,src/app/core/guards/**,src/app/core/interceptors/**,src/app/pages/board/board-view/**,src/app/pages/board/card-detail/**,src/app/pages/board/archive-manager/**,src/app/pages/workspace/workspace-detail/**,src/app/pages/dashboard/dashboard/**,src/app/pages/dashboard/search/**,src/app/pages/profile/**,src/app/shared/components/**
sonar.javascript.lcov.reportPaths=coverage/flowboard-frontend/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.host.url=http://localhost:9000
